"""Make hrga column on User table nullable

Revision ID: 13cebf31e315
Revises: bd5687349a24
Create Date: 2024-08-12 18:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13cebf31e315'
down_revision = 'bd5687349a24'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted for SQLite support ###
    # We use batch_alter_table for SQLite compatibility when altering constraints.
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('hrga',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - adjusted for SQLite support ###
    # We use batch_alter_table for SQLite compatibility when altering constraints.
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('hrga',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
