"""Add onboarding fields to User model + Name change: hrga -> hla

Revision ID: 2184dd810656
Revises: 2937ccecbda3
Create Date: 2025-08-28 17:41:00.708919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2184dd810656'
down_revision: Union[str, Sequence[str], None] = '2937ccecbda3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None)as batch_op:
        batch_op.add_column(sa.Column('hla', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('vision', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('milestone', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('constraint', sa.Text(), nullable=True))
        batch_op.drop_column('hrga')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None)as batch_op:
        batch_op.add_column(sa.Column('hrga', sa.TEXT(), nullable=True))
        batch_op.drop_column('constraint')
        batch_op.drop_column('milestone')
        batch_op.drop_column('vision')
        batch_op.drop_column('hla')
    # ### end Alembic commands ###
