"""Add streak fields to user model

Revision ID: 2937ccecbda3
Revises: 21769d6ff04a
Create Date: 2025-08-26 12:48:27.132731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2937ccecbda3'
down_revision: Union[str, Sequence[str], None] = '21769d6ff04a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_streak', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('longest_streak', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('last_streak_update', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('users', 'last_streak_update')
        batch_op.drop_column('users', 'longest_streak')
        batch_op.drop_column('users', 'current_streak')
    # ### end Alembic commands ###
