"""Add V2 onboarding fields to User model

Revision ID: 82a077b1a2b1
Revises: 2184dd810656
Create Date: 2025-09-10 17:36:44.230556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82a077b1a2b1'
down_revision: Union[str, Sequence[str], None] = '2184dd810656'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_stage', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('stretch_goal', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('primary_constraint', sa.String(length=50), nullable=True))
        batch_op.drop_column('vision')
        batch_op.drop_column('milestone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('milestone', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('vision', sa.TEXT(), nullable=True))
        batch_op.drop_column('primary_constraint')
        batch_op.drop_column('stretch_goal')
        batch_op.drop_column('business_stage')
    # ### end Alembic commands ###
